name: saas-monorepo-dev

services:
  postgres:
    image: postgres:18
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql
  
  files:
    image: rustfs/rustfs:latest
    container_name: local-files
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: true
    ports:
      - 9000:9000 # S3 API
      - 9001:9001 # Http Console
    volumes:
      - files_data:/data

volumes:
  postgres_data:
  files_data:
