name: saas-monorepo-dev

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - 5400:5432
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./create-test-db.sql:/docker-entrypoint-initdb.d/create-test-db.sql:ro

  files:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: true
    ports:
      - 9000:9000 # S3 API
      - 9001:9001 # Http Console
    volumes:
      - files_data:/data

  files-init:
    image: amazon/aws-cli:latest
    depends_on:
      - files
    entrypoint: >
      sh -c "
      sleep 2 &&
      aws --endpoint-url=http://files:9000 s3 mb s3://super-s3-bucket &&
      echo 'Bucket created'
      "
    environment:
      AWS_ACCESS_KEY_ID: rustfsadmin
      AWS_SECRET_ACCESS_KEY: rustfsadmin

volumes:
  postgres_data:
  files_data:
